name: Lint Codebase

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  other-linter:
    name: Lint Others
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: setup aqua
        uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
        with:
          aqua_version: v2.28.0
          aqua_opts: ""

      - name: Lint GitHub Action
        run: |
          ghalint run-action

      - name: Lint GitHub Actions workflows
        run: |
          ghalint run

  super-linter:
    name: Lint Codebase
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: load env for super-linter
        run: |
          grep -v '#' superlinter.env >> "$GITHUB_ENV"
        working-directory: ${{ github.workspace }}/.github/linters

      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@85f7611e0f7b53c8573cca84aa0ed4344f6f6a4d # v7.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
