name: Release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 10
    steps:
      # release by GitHub App to trigger after events.
      - uses: actions/create-github-app-token@136412a57a7081aa63c935a2cc2918f76c34f514 # v1.11.2
        id: app-token
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        id: release-please
        with:
          release-type: node
          token: ${{ steps.app-token.outputs.token }}

      - name: get app information
        id: app-info
        run: |
          echo "app-user-id=$(gh api "/users/${APP_SLUG}[bot]" --jq .id)" >> "${GITHUB_OUTPUT}"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          persistent-credentials: true

      - name: config git user
        run: |
          git config user.name "${GIT_USER_NAME}"
          git config user.email "${GIT_USER_EMAIL}"
        env:
          GIT_USER_NAME: "${{ steps.app-token.outputs.app-slug }}[bot]"
          GIT_USER_EMAIL: "${{ steps.app-info.outputs.app-user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"

      # https://github.com/googleapis/release-please-action?tab=readme-ov-file#creating-majorminor-tags
      - name: update major and minor tags
        if: steps.release-please.outputs.release_created == 'true'
        run: |
          git tag -d "v${MAJOR_VERSION}" || true
          git tag -d "v${MAJOR_VERSION}.${MINOR_VERSION}" || true
          git push --delete origin "v${MAJOR_VERSION}" || true
          git push --delete origin "v${MAJOR_VERSION}.${MINOR_VERSION}" || true

          git fetch --tags
          git tag -a "v${MAJOR_VERSION}" -m "Release v${MAJOR_VERSION}"
          git tag -a "v${MAJOR_VERSION}.${MINOR_VERSION}" -m "Release v${MAJOR_VERSION}.${MINOR_VERSION}"
          git push origin --tags
        env:
          MAJOR_VERSION: ${{ steps.release-please.outputs.major }}
          MINOR_VERSION: ${{ steps.release-please.outputs.minor }}
